pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'https://index.docker.io/v1/'
        DOCKERHUB_CREDENTIALS = 'dockerhub'
        TAG = 'web'
        DOCKERFILE_FOLDER = 'SHOP-WEB'
       
    }

    stages {
        stage('Clone repository') {
            steps {
                checkout scm
            }
        }

        stage('Build image') {
            steps {
                script {
                    docker.build("attamegnon/attamegnon2022:${TAG}_v0.0${env.BUILD_NUMBER}", "-f ${DOCKERFILE_FOLDER}/Dockerfile .")
                    // Additional build steps if needed
                }
            }
        }

        stage('Push image to DockerHub and remove local image') {
            steps {
                script {
                    docker.withRegistry(DOCKER_REGISTRY, DOCKERHUB_CREDENTIALS) {
                        sh "docker push attamegnon/attamegnon2022:${TAG}_v0.0${env.BUILD_NUMBER}"
                        sh "docker images"
                        sh "docker rmi -f attamegnon/attamegnon2022:${TAG}_v0.0${env.BUILD_NUMBER}"
                        sh "docker images"
                    }
                }
            }
        }

        stage('Trigger ManifestUpdate') {
            steps {
                script {
                    FUNCTION = "${TAG}_v0.0${env.BUILD_NUMBER}"
                    echo "Triggering updatemanifestjob with DOCKERTAG=${FUNCTION}"
                    build job: 'updatemanifest', parameters: [string(name: 'DOCKERTAG', value: "${FUNCTION}")]
                }
            }
        }
    }
}
