node {

    stage('Cloning CD-SHOP-PRODUCT repo') {
      

        checkout scm
    }

    stage('Updating SHOP-PRODUCT value.yaml in CD branch') {
            script {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    // fetching these credential from the jenkins credential that i set up in jenkins. the password is the token i generated in github
                    withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                        sh "git config user.email attamegnon@gmail.com"
                        sh "git config user.name s7testar"
                        sh "git switch CD"
                        sh "cd SHOP-PRODUCT"
                        sh "cat SHOP-PRODUCT/values.yaml"
                        sh "sed -i 's+tag:.*+tag: \"${DOCKERTAG}\"+g' SHOP-PRODUCT/values.yaml"
                     // sh "sed -i 's+attamegnon/attamegnon2022.*+attamegnon/attamegnon2022:${DOCKERTAG}+g' values.yaml" 
                        sh "cat SHOP-PRODUCT/values.yaml"
                        sh "cd .."  
                        sh "git config pull.rebase false"
                        sh "git pull --all" 
                        sh "git add ."
                        sh "git commit -m 'Done by Jenkins Job update SHOP-PRODUCT value.yaml: ${env.BUILD_NUMBER}'"
                        sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/DEL-ORG/CI-jenkins_CD-argo-S7Auriole.git HEAD:CD"
      }
    }
  }
}
}
